django_link_portal/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from portal.views import portal_index

urlpatterns = [
    path("portal/", include("portal.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/urls.py
from django.urls import path
from .views import portal_about, portal_add_category, portal_add_page, portal_index, portal_show_category


app_name = "portal"

urlpatterns = [
    path("", portal_index, name="portal_index"),
    path("about/", portal_about, name="portal_about"),
    path("add_category/", portal_add_category, name="portal_add_category"),
    path("category/<slug:slug>/", portal_show_category, name="portal_show_category"),
    path("category/<slug:slug>/add_page/", portal_add_page, name="portal_add_page"),
]

portal/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # one to one mapping so an instance of userprofile will be linked to a user model instance
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # the additional attributes to be added that the defualt user model does not provide.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to="profile_images", blank=True)

    def __str__(self):
        return self.user.username

portal/forms.py
from django import forms
from django.contrib.auth.models import User
from portal.models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="enter a category name")

    class Meta:
        model = Category
        fields = ("name",)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="enter a page title")
    url = forms.URLField(max_length=200, help_text="please enter a valid URL (http:// or https://)")

    class Meta:
        model = Page
        exclude = ("category", "views",)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password",)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("website", "picture",)

portal/views.py
from django.shortcuts import redirect, render, reverse
from .models import Category, Page
from .forms import CategoryForm, PageForm


def portal_about(request):
    print(request.method)
    print(request.user)
    print(request.user.is_authenticated)
    return render(request, "portal/about.html", {"aboutmessage": "welcome to about page."})


def portal_index(request):
    category_list = Category.objects.order_by("-likes")
    page_list = Page.objects.order_by("-views")[:5]
    context = {"boldmessage": "why hello there", "category_list": category_list, "page_list": page_list}
    return render(request, "portal/index.html", context=context)


def portal_show_category(request, slug):
    context = {}

    try:
        category = Category.objects.get(slug=slug)
        pages = Page.objects.filter(category=category)
        context["category"] = category
        context["pages"] = pages

    except Category.DoesNotExist:
        context["category"] = None
        context["pages"] = None

    return render(request, "portal/category.html", context=context)


def portal_add_category(request):
    form = CategoryForm()

    if request.method == "POST":
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect("/portal/")
        else:
            print(form.errors)
    return render(request, "portal/add_category.html", {"form": form})


def portal_add_page(request, slug):
    try:
        category = Category.objects.get(slug=slug)
    except Category.DoesNotExist:
        category = None

    if category is None:
        return redirect('/portal/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.save()
                return redirect(reverse('portal:portal_show_category',
                                        kwargs={'slug': slug}))
    else:
        print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'portal/add_page.html', context=context_dict)

portal/templates/portal/about.html
<!DOCTYPE HTML>
{% load staticfiles %}
<html>
<head>
<title>about page</title>
</head>
<body>
{{aboutmessage}}
<img src="{%static 'images/girbot.jpg'%}"/>
<img src="{{ MEDIA_URL }}girpool.jpeg"/>
</body>
</html>

portal/templates/portal/add_category.html
<!DOCTYPE HTML>
<html>
<head><title>ADD CATEGORY</title></head>
<body>
    <div>
        <h1>Add a Category</h1>
        <form id="category_form" method="post" action="{% url 'portal:portal_add_category' %}">
            {% csrf_token %}
            {% for visible_field in form.visible_fields %}
                {{ visible_field.errors }}
                {{ visible_field.help_text }}
                {{ visible_field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category">
        </form>
    </div>
</body>
</html>

portal/templates/portal/add_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add New Page</title>
</head>
<body>
    <div>
        <h1>Add a Page</h1>
            <form id="page_form" method="post" action="{% url 'portal:portal_add_page' category.slug %}">
            {% csrf_token %}
            {% for visible_field in form.visible_fields %}
                {{ visible_field.errors }}
                {{ visible_field.help_text }}
                {{ visible_field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Page">
        </form>
    </div>
</body>
</html>

portal/templates/portal/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load portal_template_tags %}
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>Django Link Portal</title>
    </head>

    <body>
        <div>
            {% block sidebar_block %}
            {% get_category_list category%}
            {% endblock %}
        </div>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <hr/>
        <div>
            <ul>
                <li><a href="{% url 'portal:portal_add_category' %}">add new category</a></li>
                <li><a href="{% url 'portal:portal_index' %}">home</a></li>
                <li><a href="{% url 'portal:portal_about' %}">about</a></li>
            </ul>
        </div>


    </body>

</html>

portal/templates/portal/categories.html
<ul>
    {% if categories %}
        {% for category in categories %}
            {% if category == current_category %}
                <li>
                    <strong><a href="{% url 'portal:portal_show_category' category.slug %}">{{ category.name }}</a></strong>
                </li>
            {% else %}
                <li><a href="{% url 'portal:portal_show_category' category.slug %}">{{ category.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <h1>There are no categories.</h1>
    {% endif %}
</ul>

portal/templates/portal/category.html
{%  extends 'portal/base.html' %}
{% load staticfiles %}
{% block body_block %}

    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
        {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
        {% else %}
            THERE ARE NO PAGES IN THIS CATEGORY
        {% endif %}
        <div>
            <p>
                <a href="{% url 'portal:portal_add_page' category.slug %}">Add new page to this category</a>
            </p>
        </div>

    {% else %}
        THERE IS NO CATEGORY MATCHING YOUR QUERY
    {% endif %}
{%  endblock %}

portal/templates/portal/index.html
{% extends "portal/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div>
    <h2>Categories by Popularity</h2>
    {% if category_list %}
        {% for category in category_list %}
            <li><a href="{% url 'portal:portal_show_category' category.slug %}">{{ category.name }}</a></li>
        {% endfor %}
    {% else %}
        <h2>There are no categories to display.</h2>
    {% endif %}
</div>

<div>
    {% if page_list %}
        <h2>Top 5 Viewed Pages</h2>
        {% for page in page_list %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}

    {% else %}
        <h2>Sorry, there are currently no pages.</h2>
    {% endif %}
</div>

<img src="{% static 'images/girbot.jpg' %}"/>
{% endblock %}

</body>
</html>